#!/usr/bin/env python3
"""Download precomputed sieve data (Residues.txt + Filters.txt) from the
esc-paper/erdos-straus GitHub repo.

These files are generated by the Salez algorithm (arXiv:1406.6307) and
extended in arXiv:2509.00128. Total: ~114MB.

Usage:
    python download_sieve_data.py
"""
import hashlib
import os
import sys
import urllib.request

SIEVE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sieve_data")

# GitHub raw URLs for the precomputed data
BASE_URL = "https://raw.githubusercontent.com/esc-paper/erdos-straus/main/section1/resources"

FILES = {
    "Residues.txt": {
        "url": f"{BASE_URL}/Residues.txt",
        "size_mb": 24,
    },
    "Filters.txt": {
        "url": f"{BASE_URL}/Filters.txt",
        "size_mb": 90,
    },
}


def download_file(url, dest, label=""):
    """Download a file with progress."""
    print(f"  Downloading {label}...")

    def progress_hook(block_num, block_size, total_size):
        downloaded = block_num * block_size
        if total_size > 0:
            pct = min(100, 100 * downloaded / total_size)
            mb = downloaded / 1024 / 1024
            total_mb = total_size / 1024 / 1024
            print(f"\r  {pct:5.1f}% ({mb:.1f}/{total_mb:.1f} MB)", end="", flush=True)

    urllib.request.urlretrieve(url, dest, reporthook=progress_hook)
    print()


def verify_file(path):
    """Quick sanity check — file exists and is non-empty."""
    if not os.path.exists(path):
        return False
    size = os.path.getsize(path)
    return size > 1_000_000  # at least 1MB


def main():
    os.makedirs(SIEVE_DIR, exist_ok=True)

    print("Downloading sieve precomputed data...")
    print(f"Destination: {SIEVE_DIR}")
    print()

    for filename, info in FILES.items():
        dest = os.path.join(SIEVE_DIR, filename)

        if verify_file(dest):
            size_mb = os.path.getsize(dest) / 1024 / 1024
            print(f"  {filename}: already exists ({size_mb:.1f} MB), skipping")
            continue

        download_file(info["url"], dest, label=f"{filename} (~{info['size_mb']}MB)")

        if not verify_file(dest):
            print(f"  ERROR: {filename} download failed or is too small")
            sys.exit(1)

        size_mb = os.path.getsize(dest) / 1024 / 1024
        print(f"  {filename}: OK ({size_mb:.1f} MB)")

    print()
    print("Done. Sieve data ready.")

    # Quick stats
    res_path = os.path.join(SIEVE_DIR, "Residues.txt")
    with open(res_path) as f:
        count = len(f.read().split())
    print(f"  Residues: {count:,} entries")

    fil_path = os.path.join(SIEVE_DIR, "Filters.txt")
    with open(fil_path) as f:
        content = f.read()
        # Each filter block ends with -1
        filter_count = content.count(" -1")
    print(f"  Filters: ~{filter_count:,} entries")


if __name__ == "__main__":
    main()
